### ISSUE TITLE
example jupyter notebook and examples pages give 404 error

### ISSUE THREAD

**Issue by e4BdSBmUzHowFico5Ktn** [PascalLesage/presamples#64]
The example jupyter notebook and examples pages both give a 404 error.
Could this be fixed? I would like to use Presamples and would be really happy with some good example workflows to get me up and running!

**Comment by PascalLesage** [comment]
@e4BdSBmUzHowFico5Ktn I updated the first link and deleted the reference to the second. I hope to get much better docs up soon, you can raise another issue if nothing happens to nudge me.
