### ISSUE TITLE
errors in quickstart

### ISSUE THREAD

**Issue by e4BdSBmUzHowFico5Ktn** [PascalLesage/presamples#65]
I'm following the quickstart code of the docs, and copy pasted everything so I'm pretty sure I made no mistakes.

[This section](https://presamples.readthedocs.io/en/latest/quickstart.html#loading-packages-for-use-one-column-at-a-time)  gives errors with:
`ag_loader.parameters['land' [ha]'] `
> `TypeError: list indices must be integers or slices, not str`

`ag_loader.parameters.consolidated_array`
> `AttributeError: 'list' object has no attribute 'consolidated_array'`

`ag_loader.parameters.names`
> `AttributeError: 'list' object has no attribute 'names'`

I haven't tried any further because of the errors.
Please let me know how to resolve this

**Comment by e4BdSBmUzHowFico5Ktn** [comment]
411f183 Does not fix the issue for me. I still get the same errors.

**Comment by PascalLesage** [comment]
Have you tried running the Notebook version? Do you have the same error when you do? 
If so, can you share what version of presamples, python and numpy you are using?
